name: Build and Release Module
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Install VC Build
        run: |
          dotnet tool install -g VirtoCommerce.GlobalTool

      - name: VC Build Compress
        run: |
          vc-build compress

      - name: Get Artifact Version
        uses: VirtoCommerce/vc-github-actions/get-image-version@master
        id: artifact_ver

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.artifact_ver.outputs.prefix }}
          release_name: ${{ steps.artifact_ver.outputs.prefix }}
          draft: false
          prerelease: false
          body: |
            **:target: Development** 
            *Added Features: *          
            - Product_Description_Generation: "Generate SEO-friendly product descriptions effortlessly."
            - Translation_Capabilities: "Translate product details across multiple languages."
            - Rephrasing_Features: "Refine and ensure unique product content."
            - Image_Generation: "AI-powered creation of high-quality product images."

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./artifacts/Sharpcode.AiAssistModule_${{ steps.artifact_ver.outputs.prefix }}.zip
          asset_name: Sharpcode.AiAssistModule_${{ steps.artifact_ver.outputs.prefix }}.zip
          asset_content_type: application/zip